### ISSUE TITLE
Handler, how?

### ISSUE THREAD

**Issue by MartinElvar** [brianmay/mqtt_potion#54]
Is there any examples of making a handler? There seems to be in the original exmqtt, but i don't find any behaviors to follow along.

How do i know what should be implemented in my handler?

**Comment by brianmay** [comment]
Yes, you are right, this should be documented better.

For my code I use the `Multiplexer` as a handler. See https://github.com/brianmay/scrooge/blob/main/lib/scrooge/application.ex#L25-L55 for an example.

IIRC incoming events are sent to the handler as messages.

At the moment though, trying to solve #55 is my current priority... But currently has me totally stumped.

**Comment by MartinElvar** [comment]
Thanks @brianmay, that helped a lot. :slightly_smiling_face:
